apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: microservices-stack
type: Opaque
stringData:
  POSTGRES_USER: "devuser"
  POSTGRES_PASSWORD: "devpassword"
  MONGO_INITDB_ROOT_USERNAME: "devuser"
  MONGO_INITDB_ROOT_PASSWORD: "devpassword"
  MONGO_URI: "mongodb://devuser:devpassword@mongodb:27017/catalog_db?authSource=admin"
  DATABASE_URL: "postgresql://devuser:devpassword@postgres:5432/microservices_db"
