apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    {{- include "microservices-stack.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.ports.frontend }}
      targetPort: {{ .Values.ports.frontend }}
  selector:
    app: frontend
