apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-gateway
  labels:
    app: api-gateway
    {{- include "microservices-stack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.gateway }}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: "{{ .Values.images.registry }}/{{ .Values.images.username }}/{{ .Values.images.gateway }}:{{ .Values.images.tag }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ports.gateway }}
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ports.gateway }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ports.gateway }}
            initialDelaySeconds: 5
            periodSeconds: 5
