apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-notification-service
  labels:
    app: notification-service
    {{- include "microservices-stack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.notification }}
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: "{{ .Values.images.registry }}/{{ .Values.images.username }}/{{ .Values.images.notification }}:{{ .Values.images.tag }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - containerPort: 8001
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: RABBITMQ_HOST
            - name: HEALTH_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: PORT_NOTIFICATION_HEALTH
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 5
