apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "microservices-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: "{{ .Values.databases.postgres.user }}"
  POSTGRES_PASSWORD: "{{ .Values.databases.postgres.password }}"
  MONGO_INITDB_ROOT_USERNAME: "{{ .Values.databases.mongodb.user }}"
  MONGO_INITDB_ROOT_PASSWORD: "{{ .Values.databases.mongodb.password }}"
  MONGO_URI: "mongodb://{{ .Values.databases.mongodb.user }}:{{ .Values.databases.mongodb.password }}@mongodb:27017/{{ .Values.databases.mongodb.db }}?authSource=admin"
  DATABASE_URL: "postgresql://{{ .Values.databases.postgres.user }}:{{ .Values.databases.postgres.password }}@postgres:5432/{{ .Values.databases.postgres.db }}"
