[microservices_servers]
app-server-01 ansible_host=192.168.10.11 ansible_user=ubuntu
app-server-02 ansible_host=192.168.10.12 ansible_user=ubuntu

[databases]
db-server-01 ansible_host=192.168.10.20 ansible_user=ubuntu

[production:children]
microservices_servers
databases
